CREATE DATABASE DemoSimple;
GO
USE DemoSimple;

CREATE TABLE Roles(
RoleID INT PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(90) NOT NULL UNIQUE
)
GO
CREATE TABLE Users(
UserID INT PRIMARY KEY IDENTITY(1,1),
Login NVARCHAR(90) NOT NULL UNIQUE,
Password NVARCHAR(90) NOT NULL,
UserRole INT NOT NULL REFERENCES Roles(RoleID),
FailedAttempts INT NOT NULL DEFAULT(0),
IsBlocked BIT NOT NULL DEFAULT(0)
)